/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Action38ff08ab6736100010816009079d0126;
import com.konfigthis.client.model.Comments86093b8a932f10001499f356ff83012e;
import com.konfigthis.client.model.EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143;
import com.konfigthis.client.model.For5d688bd57bb910001815ab3dd10024a9;
import com.konfigthis.client.model.OverallBusinessProcess5d688bd57bb910001815ab49927724aa;
import com.konfigthis.client.model.TransactionStatus7457adcbe0fa1000089b63ab3a510000;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BusinessProcessParameters2dcd9a4882b210000f7b2e0a85982265
 */
public class BusinessProcessParameters2dcd9a4882b210000f7b2e0a85982265Test {
    private final BusinessProcessParameters2dcd9a4882b210000f7b2e0a85982265 model = new BusinessProcessParameters2dcd9a4882b210000f7b2e0a85982265();

    /**
     * Model tests for BusinessProcessParameters2dcd9a4882b210000f7b2e0a85982265
     */
    @Test
    public void testBusinessProcessParameters2dcd9a4882b210000f7b2e0a85982265() {
        // TODO: test BusinessProcessParameters2dcd9a4882b210000f7b2e0a85982265
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'overallBusinessProcess'
     */
    @Test
    public void overallBusinessProcessTest() {
        // TODO: test overallBusinessProcess
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'transactionStatus'
     */
    @Test
    public void transactionStatusTest() {
        // TODO: test transactionStatus
    }

    /**
     * Test the property 'warningValidations'
     */
    @Test
    public void warningValidationsTest() {
        // TODO: test warningValidations
    }

    /**
     * Test the property 'overallStatus'
     */
    @Test
    public void overallStatusTest() {
        // TODO: test overallStatus
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

    /**
     * Test the property 'criticalValidations'
     */
    @Test
    public void criticalValidationsTest() {
        // TODO: test criticalValidations
    }

    /**
     * Test the property '_for'
     */
    @Test
    public void _forTest() {
        // TODO: test _for
    }

}
