/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AssignmentType23929e1f68ca10000d6940d6bde56963;
import com.konfigthis.client.model.ChangeJobCompanyInsiderTypesData05d4c45042b61000131e4b2132f30137;
import com.konfigthis.client.model.PayRateTypeD25283821c01100016756a14eb650000;
import com.konfigthis.client.model.PositionWorkerType05d4c45042b610001030ee47f2c90118;
import com.konfigthis.client.model.TimeType05d4c45042b610000bb540b7458e0108;
import com.konfigthis.client.model.WorkStudy05d4c45042b610000ba2f83c70f30101;
import com.konfigthis.client.model.WorkersCompensationCodeOverride05d4c45042b61000138500e185e0013f;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
 */
public class ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOfTest {
    private final ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf model = new ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf();

    /**
     * Model tests for ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    @Test
    public void testChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf() {
        // TODO: test ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
    }

    /**
     * Test the property 'payRateType'
     */
    @Test
    public void payRateTypeTest() {
        // TODO: test payRateType
    }

    /**
     * Test the property 'workersCompensationCodeOverride'
     */
    @Test
    public void workersCompensationCodeOverrideTest() {
        // TODO: test workersCompensationCodeOverride
    }

    /**
     * Test the property 'fte'
     */
    @Test
    public void fteTest() {
        // TODO: test fte
    }

    /**
     * Test the property 'notifyBy'
     */
    @Test
    public void notifyByTest() {
        // TODO: test notifyBy
    }

    /**
     * Test the property 'companyInsiderTypes'
     */
    @Test
    public void companyInsiderTypesTest() {
        // TODO: test companyInsiderTypes
    }

    /**
     * Test the property 'firstDayOfWork'
     */
    @Test
    public void firstDayOfWorkTest() {
        // TODO: test firstDayOfWork
    }

    /**
     * Test the property 'defaultWeeklyHours'
     */
    @Test
    public void defaultWeeklyHoursTest() {
        // TODO: test defaultWeeklyHours
    }

    /**
     * Test the property 'positionWorkerType'
     */
    @Test
    public void positionWorkerTypeTest() {
        // TODO: test positionWorkerType
    }

    /**
     * Test the property 'workingFte'
     */
    @Test
    public void workingFteTest() {
        // TODO: test workingFte
    }

    /**
     * Test the property 'specifyWorkingFte'
     */
    @Test
    public void specifyWorkingFteTest() {
        // TODO: test specifyWorkingFte
    }

    /**
     * Test the property 'timeType'
     */
    @Test
    public void timeTypeTest() {
        // TODO: test timeType
    }

    /**
     * Test the property 'specifyPaidFte'
     */
    @Test
    public void specifyPaidFteTest() {
        // TODO: test specifyPaidFte
    }

    /**
     * Test the property 'paidFte'
     */
    @Test
    public void paidFteTest() {
        // TODO: test paidFte
    }

    /**
     * Test the property 'workStudy'
     */
    @Test
    public void workStudyTest() {
        // TODO: test workStudy
    }

    /**
     * Test the property 'assignmentType'
     */
    @Test
    public void assignmentTypeTest() {
        // TODO: test assignmentType
    }

    /**
     * Test the property 'endEmploymentDate'
     */
    @Test
    public void endEmploymentDateTest() {
        // TODO: test endEmploymentDate
    }

    /**
     * Test the property 'expectedAssignmentEndDate'
     */
    @Test
    public void expectedAssignmentEndDateTest() {
        // TODO: test expectedAssignmentEndDate
    }

}
