/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.JobRequisitionDfc4e58f730810001ad60325d9bc52cf;
import com.konfigthis.client.model.PositionDfc4e58f730810001ad60369c23452d1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221
 */
public class ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221Test {
    private final ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221 model = new ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221();

    /**
     * Model tests for ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221
     */
    @Test
    public void testChangeJobPositionDataDfc4e58f7308100018bd1c459f435221() {
        // TODO: test ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221
    }

    /**
     * Test the property 'createPosition'
     */
    @Test
    public void createPositionTest() {
        // TODO: test createPosition
    }

    /**
     * Test the property 'availableForOverlap'
     */
    @Test
    public void availableForOverlapTest() {
        // TODO: test availableForOverlap
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'closePosition'
     */
    @Test
    public void closePositionTest() {
        // TODO: test closePosition
    }

    /**
     * Test the property 'jobRequisition'
     */
    @Test
    public void jobRequisitionTest() {
        // TODO: test jobRequisition
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
