/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Location90151d6c4ff110001bfa027116820278;
import com.konfigthis.client.model.WorkShift0ee7bb8b41db1000143d4e4822174f2e;
import com.konfigthis.client.model.WorkSpace0ee7bb8b41db10001e7db6a6c3e55663;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ChangeJobLocation90151d6c4ff110001b4a46091678025cAllOf
 */
public class ChangeJobLocation90151d6c4ff110001b4a46091678025cAllOfTest {
    private final ChangeJobLocation90151d6c4ff110001b4a46091678025cAllOf model = new ChangeJobLocation90151d6c4ff110001b4a46091678025cAllOf();

    /**
     * Model tests for ChangeJobLocation90151d6c4ff110001b4a46091678025cAllOf
     */
    @Test
    public void testChangeJobLocation90151d6c4ff110001b4a46091678025cAllOf() {
        // TODO: test ChangeJobLocation90151d6c4ff110001b4a46091678025cAllOf
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'scheduledHours'
     */
    @Test
    public void scheduledHoursTest() {
        // TODO: test scheduledHours
    }

    /**
     * Test the property 'workShift'
     */
    @Test
    public void workShiftTest() {
        // TODO: test workShift
    }

    /**
     * Test the property 'workSpace'
     */
    @Test
    public void workSpaceTest() {
        // TODO: test workSpace
    }

}
