/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.HeadcountOption97af9049a5fd10001c48896fbde30000;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ChangeJobOpeningData97af9049a5fd10001c4888d654170000AllOf
 */
public class ChangeJobOpeningData97af9049a5fd10001c4888d654170000AllOfTest {
    private final ChangeJobOpeningData97af9049a5fd10001c4888d654170000AllOf model = new ChangeJobOpeningData97af9049a5fd10001c4888d654170000AllOf();

    /**
     * Model tests for ChangeJobOpeningData97af9049a5fd10001c4888d654170000AllOf
     */
    @Test
    public void testChangeJobOpeningData97af9049a5fd10001c4888d654170000AllOf() {
        // TODO: test ChangeJobOpeningData97af9049a5fd10001c4888d654170000AllOf
    }

    /**
     * Test the property 'headcountOption'
     */
    @Test
    public void headcountOptionTest() {
        // TODO: test headcountOption
    }

    /**
     * Test the property 'openingAvailableForOverlap'
     */
    @Test
    public void openingAvailableForOverlapTest() {
        // TODO: test openingAvailableForOverlap
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
