/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AssociatedCheckInsSummaryD81c816de26f10000f7a29ea89140020;
import com.konfigthis.client.model.CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1;
import com.konfigthis.client.model.CreatorD81c816de26f10000f521459ac80001d;
import com.konfigthis.client.model.ParticipantD81c816de26f10000f52144d053f001b;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf
 */
public class CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOfTest {
    private final CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf model = new CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf();

    /**
     * Model tests for CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf
     */
    @Test
    public void testCheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf() {
        // TODO: test CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf
    }

    /**
     * Test the property 'sharedNotes'
     */
    @Test
    public void sharedNotesTest() {
        // TODO: test sharedNotes
    }

    /**
     * Test the property 'privateNotes'
     */
    @Test
    public void privateNotesTest() {
        // TODO: test privateNotes
    }

    /**
     * Test the property 'archived'
     */
    @Test
    public void archivedTest() {
        // TODO: test archived
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'checkInTopicAttachments'
     */
    @Test
    public void checkInTopicAttachmentsTest() {
        // TODO: test checkInTopicAttachments
    }

    /**
     * Test the property 'participant'
     */
    @Test
    public void participantTest() {
        // TODO: test participant
    }

    /**
     * Test the property 'associatedCheckIns'
     */
    @Test
    public void associatedCheckInsTest() {
        // TODO: test associatedCheckIns
    }

    /**
     * Test the property 'creator'
     */
    @Test
    public void creatorTest() {
        // TODO: test creator
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
