/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AssociatedCheckInTopicDetail316b5a26cc3c100010a01184c23902ea;
import com.konfigthis.client.model.CheckInAttachmentDetailEf244acfe6cf10002ebe92d43a7701d7;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CheckInDetail316b5a26cc3c10000ebdb0cb484602e1
 */
public class CheckInDetail316b5a26cc3c10000ebdb0cb484602e1Test {
    private final CheckInDetail316b5a26cc3c10000ebdb0cb484602e1 model = new CheckInDetail316b5a26cc3c10000ebdb0cb484602e1();

    /**
     * Model tests for CheckInDetail316b5a26cc3c10000ebdb0cb484602e1
     */
    @Test
    public void testCheckInDetail316b5a26cc3c10000ebdb0cb484602e1() {
        // TODO: test CheckInDetail316b5a26cc3c10000ebdb0cb484602e1
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'associatedTopics'
     */
    @Test
    public void associatedTopicsTest() {
        // TODO: test associatedTopics
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'checkInAttachments'
     */
    @Test
    public void checkInAttachmentsTest() {
        // TODO: test checkInAttachments
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
