/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CountryAf21e47ff7c01000092ecf4d7ad30270
 */
public class CountryAf21e47ff7c01000092ecf4d7ad30270Test {
    private final CountryAf21e47ff7c01000092ecf4d7ad30270 model = new CountryAf21e47ff7c01000092ecf4d7ad30270();

    /**
     * Model tests for CountryAf21e47ff7c01000092ecf4d7ad30270
     */
    @Test
    public void testCountryAf21e47ff7c01000092ecf4d7ad30270() {
        // TODO: test CountryAf21e47ff7c01000092ecf4d7ad30270
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
