/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExternalSkillLevelDetail1c67ac98c0f310002706be33dcdb0000
 */
public class ExternalSkillLevelDetail1c67ac98c0f310002706be33dcdb0000Test {
    private final ExternalSkillLevelDetail1c67ac98c0f310002706be33dcdb0000 model = new ExternalSkillLevelDetail1c67ac98c0f310002706be33dcdb0000();

    /**
     * Model tests for ExternalSkillLevelDetail1c67ac98c0f310002706be33dcdb0000
     */
    @Test
    public void testExternalSkillLevelDetail1c67ac98c0f310002706be33dcdb0000() {
        // TODO: test ExternalSkillLevelDetail1c67ac98c0f310002706be33dcdb0000
    }

    /**
     * Test the property 'externalSkillName'
     */
    @Test
    public void externalSkillNameTest() {
        // TODO: test externalSkillName
    }

    /**
     * Test the property 'externalSkillLevel'
     */
    @Test
    public void externalSkillLevelTest() {
        // TODO: test externalSkillLevel
    }

    /**
     * Test the property 'skillVendorName'
     */
    @Test
    public void skillVendorNameTest() {
        // TODO: test skillVendorName
    }

    /**
     * Test the property 'skillVendorId'
     */
    @Test
    public void skillVendorIdTest() {
        // TODO: test skillVendorId
    }

    /**
     * Test the property 'context'
     */
    @Test
    public void contextTest() {
        // TODO: test context
    }

    /**
     * Test the property 'effectiveMoment'
     */
    @Test
    public void effectiveMomentTest() {
        // TODO: test effectiveMoment
    }

    /**
     * Test the property 'externalSkillId'
     */
    @Test
    public void externalSkillIdTest() {
        // TODO: test externalSkillId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
