/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Job75e528a78e9a10000ab7512c5c550115;
import com.konfigthis.client.model.Location75e528a78e9a10000ab75125ebe50114;
import com.konfigthis.client.model.Reason85deac43cd1a10000b96c80c118f171e;
import com.konfigthis.client.model.SupervisoryOrganization75e528a78e9a10000ab75132a9df0116;
import com.konfigthis.client.model.Template2b1b95dfe4af100007f63081aec5158e;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobChangesStartDetailsPOSTData75e528a78e9a10000ab750ea156f0111
 */
public class JobChangesStartDetailsPOSTData75e528a78e9a10000ab750ea156f0111Test {
    private final JobChangesStartDetailsPOSTData75e528a78e9a10000ab750ea156f0111 model = new JobChangesStartDetailsPOSTData75e528a78e9a10000ab750ea156f0111();

    /**
     * Model tests for JobChangesStartDetailsPOSTData75e528a78e9a10000ab750ea156f0111
     */
    @Test
    public void testJobChangesStartDetailsPOSTData75e528a78e9a10000ab750ea156f0111() {
        // TODO: test JobChangesStartDetailsPOSTData75e528a78e9a10000ab750ea156f0111
    }

    /**
     * Test the property 'supervisoryOrganization'
     */
    @Test
    public void supervisoryOrganizationTest() {
        // TODO: test supervisoryOrganization
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'job'
     */
    @Test
    public void jobTest() {
        // TODO: test job
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
