/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.JobFamilyGroup51ed1475e9e6100006229cfe817b0014;
import com.konfigthis.client.model.JobProfileView51ed1475e9e6100006c698ef68480017;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobFamilyView51ed1475e9e6100005d10fcedc5a000a
 */
public class JobFamilyView51ed1475e9e6100005d10fcedc5a000aTest {
    private final JobFamilyView51ed1475e9e6100005d10fcedc5a000a model = new JobFamilyView51ed1475e9e6100005d10fcedc5a000a();

    /**
     * Model tests for JobFamilyView51ed1475e9e6100005d10fcedc5a000a
     */
    @Test
    public void testJobFamilyView51ed1475e9e6100005d10fcedc5a000a() {
        // TODO: test JobFamilyView51ed1475e9e6100005d10fcedc5a000a
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'inactive'
     */
    @Test
    public void inactiveTest() {
        // TODO: test inactive
    }

    /**
     * Test the property 'jobFamilyGroup'
     */
    @Test
    public void jobFamilyGroupTest() {
        // TODO: test jobFamilyGroup
    }

    /**
     * Test the property 'jobProfiles'
     */
    @Test
    public void jobProfilesTest() {
        // TODO: test jobProfiles
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
