/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CountryOrRegion3b00708994e4100007848bc917a112a6;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobProfileExemptRelatedView3b00708994e41000076da515387812a2AllOf
 */
public class JobProfileExemptRelatedView3b00708994e41000076da515387812a2AllOfTest {
    private final JobProfileExemptRelatedView3b00708994e41000076da515387812a2AllOf model = new JobProfileExemptRelatedView3b00708994e41000076da515387812a2AllOf();

    /**
     * Model tests for JobProfileExemptRelatedView3b00708994e41000076da515387812a2AllOf
     */
    @Test
    public void testJobProfileExemptRelatedView3b00708994e41000076da515387812a2AllOf() {
        // TODO: test JobProfileExemptRelatedView3b00708994e41000076da515387812a2AllOf
    }

    /**
     * Test the property 'countryOrRegion'
     */
    @Test
    public void countryOrRegionTest() {
        // TODO: test countryOrRegion
    }

    /**
     * Test the property 'exempt'
     */
    @Test
    public void exemptTest() {
        // TODO: test exempt
    }

}
