/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobTypeB8ac205877fd100005c55b45c6400057
 */
public class JobTypeB8ac205877fd100005c55b45c6400057Test {
    private final JobTypeB8ac205877fd100005c55b45c6400057 model = new JobTypeB8ac205877fd100005c55b45c6400057();

    /**
     * Model tests for JobTypeB8ac205877fd100005c55b45c6400057
     */
    @Test
    public void testJobTypeB8ac205877fd100005c55b45c6400057() {
        // TODO: test JobTypeB8ac205877fd100005c55b45c6400057
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
