/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CostCenter5aabf8e28cb3100010a999f40b07024f;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrganizationAssignmentChangesCostCenterData5aabf8e28cb3100010a999db2700024e
 */
public class OrganizationAssignmentChangesCostCenterData5aabf8e28cb3100010a999db2700024eTest {
    private final OrganizationAssignmentChangesCostCenterData5aabf8e28cb3100010a999db2700024e model = new OrganizationAssignmentChangesCostCenterData5aabf8e28cb3100010a999db2700024e();

    /**
     * Model tests for OrganizationAssignmentChangesCostCenterData5aabf8e28cb3100010a999db2700024e
     */
    @Test
    public void testOrganizationAssignmentChangesCostCenterData5aabf8e28cb3100010a999db2700024e() {
        // TODO: test OrganizationAssignmentChangesCostCenterData5aabf8e28cb3100010a999db2700024e
    }

    /**
     * Test the property 'costCenter'
     */
    @Test
    public void costCenterTest() {
        // TODO: test costCenter
    }

}
