/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BusinessUnit5aabf8e28cb310002520b2aabc470366;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrganizationAssignmentChangesBusinessUnitData5aabf8e28cb310002520b2a2b31d0365AllOf
 */
public class OrganizationAssignmentChangesBusinessUnitData5aabf8e28cb310002520b2a2b31d0365AllOfTest {
    private final OrganizationAssignmentChangesBusinessUnitData5aabf8e28cb310002520b2a2b31d0365AllOf model = new OrganizationAssignmentChangesBusinessUnitData5aabf8e28cb310002520b2a2b31d0365AllOf();

    /**
     * Model tests for OrganizationAssignmentChangesBusinessUnitData5aabf8e28cb310002520b2a2b31d0365AllOf
     */
    @Test
    public void testOrganizationAssignmentChangesBusinessUnitData5aabf8e28cb310002520b2a2b31d0365AllOf() {
        // TODO: test OrganizationAssignmentChangesBusinessUnitData5aabf8e28cb310002520b2a2b31d0365AllOf
    }

    /**
     * Test the property 'businessUnit'
     */
    @Test
    public void businessUnitTest() {
        // TODO: test businessUnit
    }

}
