/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Superior643e3a1262971000145238b2ccd10059;
import com.konfigthis.client.model.SupervisoryOrganizationViewA02c2e1916fa100009e137235f1f0018;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrgChartView643e3a12629710000554e0338e670044AllOf
 */
public class OrgChartView643e3a12629710000554e0338e670044AllOfTest {
    private final OrgChartView643e3a12629710000554e0338e670044AllOf model = new OrgChartView643e3a12629710000554e0338e670044AllOf();

    /**
     * Model tests for OrgChartView643e3a12629710000554e0338e670044AllOf
     */
    @Test
    public void testOrgChartView643e3a12629710000554e0338e670044AllOf() {
        // TODO: test OrgChartView643e3a12629710000554e0338e670044AllOf
    }

    /**
     * Test the property 'superior'
     */
    @Test
    public void superiorTest() {
        // TODO: test superior
    }

    /**
     * Test the property 'subordinates'
     */
    @Test
    public void subordinatesTest() {
        // TODO: test subordinates
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
