/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PersonDataViewBe343791f59d100028d6a277ca8a0017AllOf
 */
public class PersonDataViewBe343791f59d100028d6a277ca8a0017AllOfTest {
    private final PersonDataViewBe343791f59d100028d6a277ca8a0017AllOf model = new PersonDataViewBe343791f59d100028d6a277ca8a0017AllOf();

    /**
     * Model tests for PersonDataViewBe343791f59d100028d6a277ca8a0017AllOf
     */
    @Test
    public void testPersonDataViewBe343791f59d100028d6a277ca8a0017AllOf() {
        // TODO: test PersonDataViewBe343791f59d100028d6a277ca8a0017AllOf
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
