/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SkillItem4b4b7d34b4a210001c7927f9e1330080;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SkillItemAddDefinitionFaed9891d75a10001e9a289910540228AllOf
 */
public class SkillItemAddDefinitionFaed9891d75a10001e9a289910540228AllOfTest {
    private final SkillItemAddDefinitionFaed9891d75a10001e9a289910540228AllOf model = new SkillItemAddDefinitionFaed9891d75a10001e9a289910540228AllOf();

    /**
     * Model tests for SkillItemAddDefinitionFaed9891d75a10001e9a289910540228AllOf
     */
    @Test
    public void testSkillItemAddDefinitionFaed9891d75a10001e9a289910540228AllOf() {
        // TODO: test SkillItemAddDefinitionFaed9891d75a10001e9a289910540228AllOf
    }

    /**
     * Test the property 'skillName'
     */
    @Test
    public void skillNameTest() {
        // TODO: test skillName
    }

    /**
     * Test the property 'skillItem'
     */
    @Test
    public void skillItemTest() {
        // TODO: test skillItem
    }

    /**
     * Test the property 'remoteID'
     */
    @Test
    public void remoteIDTest() {
        // TODO: test remoteID
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
