/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkSpace426ac445037110001b3eb91ddf6f0100
 */
public class WorkSpace426ac445037110001b3eb91ddf6f0100Test {
    private final WorkSpace426ac445037110001b3eb91ddf6f0100 model = new WorkSpace426ac445037110001b3eb91ddf6f0100();

    /**
     * Model tests for WorkSpace426ac445037110001b3eb91ddf6f0100
     */
    @Test
    public void testWorkSpace426ac445037110001b3eb91ddf6f0100() {
        // TODO: test WorkSpace426ac445037110001b3eb91ddf6f0100
    }

    /**
     * Test the property 'locationChain'
     */
    @Test
    public void locationChainTest() {
        // TODO: test locationChain
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
