/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Country3b00708994e4100004edeb4e0d37128c;
import com.konfigthis.client.model.LocationDataJobView6d3eb084b4c410002b5fa13f0c9d0056;
import com.konfigthis.client.model.RegionRelatedView3b00708994e41000053151ffd9e31293;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287
 */
public class WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287Test {
    private final WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287 model = new WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287();

    /**
     * Model tests for WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287
     */
    @Test
    public void testWorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287() {
        // TODO: test WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287
    }

    /**
     * Test the property 'inactive'
     */
    @Test
    public void inactiveTest() {
        // TODO: test inactive
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'regions'
     */
    @Test
    public void regionsTest() {
        // TODO: test regions
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'locations'
     */
    @Test
    public void locationsTest() {
        // TODO: test locations
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
