/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CompanyInsiderTypeRelatedView7deab99f645f10001000f8a388740081;
import com.konfigthis.client.model.CountryRelatedView7deab99f645f10000cf305c30e260054;
import com.konfigthis.client.model.DifficultyToFill89a0b59e7cce1000074acb57c0c50162;
import com.konfigthis.client.model.JobCategory89a0b59e7cce1000074acb471919015f;
import com.konfigthis.client.model.JobFamilyRelatedView3b00708994e410000e0e2540529b12d6;
import com.konfigthis.client.model.JobLevel89a0b59e7cce1000074acb3c1e8e015d;
import com.konfigthis.client.model.JobProfileExemptRelatedView3b00708994e41000076da515387812a2;
import com.konfigthis.client.model.JobProfilePayRateTypeRelatedView3b00708994e4100008d4b09e903f12b5;
import com.konfigthis.client.model.ManagementLevel89a0b59e7cce1000074acb1d768e0158;
import com.konfigthis.client.model.WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf {
  public static final String SERIALIZED_NAME_SUMMARY = "summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  private String summary;

  public static final String SERIALIZED_NAME_JOB_DESCRIPTION = "jobDescription";
  @SerializedName(SERIALIZED_NAME_JOB_DESCRIPTION)
  private String jobDescription;

  public static final String SERIALIZED_NAME_INACTIVE = "inactive";
  @SerializedName(SERIALIZED_NAME_INACTIVE)
  private Boolean inactive;

  public static final String SERIALIZED_NAME_PUBLIC = "public";
  @SerializedName(SERIALIZED_NAME_PUBLIC)
  private Boolean _public;

  public static final String SERIALIZED_NAME_JOB_LEVEL = "jobLevel";
  @SerializedName(SERIALIZED_NAME_JOB_LEVEL)
  private JobLevel89a0b59e7cce1000074acb3c1e8e015d jobLevel;

  public static final String SERIALIZED_NAME_MANAGEMENT_LEVEL = "managementLevel";
  @SerializedName(SERIALIZED_NAME_MANAGEMENT_LEVEL)
  private ManagementLevel89a0b59e7cce1000074acb1d768e0158 managementLevel;

  public static final String SERIALIZED_NAME_CRITICAL_JOB = "criticalJob";
  @SerializedName(SERIALIZED_NAME_CRITICAL_JOB)
  private Boolean criticalJob;

  public static final String SERIALIZED_NAME_JOB_EXEMPTS = "jobExempts";
  @SerializedName(SERIALIZED_NAME_JOB_EXEMPTS)
  private List<JobProfileExemptRelatedView3b00708994e41000076da515387812a2> jobExempts = null;

  public static final String SERIALIZED_NAME_COMPANY_INSIDER_TYPES = "companyInsiderTypes";
  @SerializedName(SERIALIZED_NAME_COMPANY_INSIDER_TYPES)
  private List<CompanyInsiderTypeRelatedView7deab99f645f10001000f8a388740081> companyInsiderTypes = null;

  public static final String SERIALIZED_NAME_DEFAULT_JOB_TITLE = "defaultJobTitle";
  @SerializedName(SERIALIZED_NAME_DEFAULT_JOB_TITLE)
  private String defaultJobTitle;

  public static final String SERIALIZED_NAME_WORK_SHIFT_REQUIRED = "workShiftRequired";
  @SerializedName(SERIALIZED_NAME_WORK_SHIFT_REQUIRED)
  private Boolean workShiftRequired;

  public static final String SERIALIZED_NAME_ADDITIONAL_JOB_DESCRIPTION = "additionalJobDescription";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_JOB_DESCRIPTION)
  private String additionalJobDescription;

  public static final String SERIALIZED_NAME_JOB_FAMILIES = "jobFamilies";
  @SerializedName(SERIALIZED_NAME_JOB_FAMILIES)
  private List<JobFamilyRelatedView3b00708994e410000e0e2540529b12d6> jobFamilies = null;

  public static final String SERIALIZED_NAME_DIFFICULTY_TO_FILL = "difficultyToFill";
  @SerializedName(SERIALIZED_NAME_DIFFICULTY_TO_FILL)
  private DifficultyToFill89a0b59e7cce1000074acb57c0c50162 difficultyToFill;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_JOB_CATEGORY = "jobCategory";
  @SerializedName(SERIALIZED_NAME_JOB_CATEGORY)
  private JobCategory89a0b59e7cce1000074acb471919015f jobCategory;

  public static final String SERIALIZED_NAME_PAY_RATE_TYPES = "payRateTypes";
  @SerializedName(SERIALIZED_NAME_PAY_RATE_TYPES)
  private List<JobProfilePayRateTypeRelatedView3b00708994e4100008d4b09e903f12b5> payRateTypes = null;

  public static final String SERIALIZED_NAME_RESTRICTED_TO_COUNTRIES = "restrictedToCountries";
  @SerializedName(SERIALIZED_NAME_RESTRICTED_TO_COUNTRIES)
  private List<CountryRelatedView7deab99f645f10000cf305c30e260054> restrictedToCountries = null;

  public static final String SERIALIZED_NAME_WORKERS_COMPENSATION_CODES = "workersCompensationCodes";
  @SerializedName(SERIALIZED_NAME_WORKERS_COMPENSATION_CODES)
  private List<WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287> workersCompensationCodes = null;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf() {
  }

  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf summary(String summary) {
    
    
    
    
    this.summary = summary;
    return this;
  }

   /**
   * The description of the responsibilities and/or qualifications for the job profile.
   * @return summary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The description of the responsibilities and/or qualifications for the job profile.")

  public String getSummary() {
    return summary;
  }


  public void setSummary(String summary) {
    
    
    
    this.summary = summary;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf jobDescription(String jobDescription) {
    
    
    
    
    this.jobDescription = jobDescription;
    return this;
  }

   /**
   * The formatted job description value on the job profile.
   * @return jobDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The formatted job description value on the job profile.")

  public String getJobDescription() {
    return jobDescription;
  }


  public void setJobDescription(String jobDescription) {
    
    
    
    this.jobDescription = jobDescription;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf inactive(Boolean inactive) {
    
    
    
    
    this.inactive = inactive;
    return this;
  }

   /**
   * Returns true if the Job Profile is inactive.
   * @return inactive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Returns true if the Job Profile is inactive.")

  public Boolean getInactive() {
    return inactive;
  }


  public void setInactive(Boolean inactive) {
    
    
    
    this.inactive = inactive;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf _public(Boolean _public) {
    
    
    
    
    this._public = _public;
    return this;
  }

   /**
   * Indicates if the job profile has been marked as being public.
   * @return _public
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Indicates if the job profile has been marked as being public.")

  public Boolean getPublic() {
    return _public;
  }


  public void setPublic(Boolean _public) {
    
    
    
    this._public = _public;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf jobLevel(JobLevel89a0b59e7cce1000074acb3c1e8e015d jobLevel) {
    
    
    
    
    this.jobLevel = jobLevel;
    return this;
  }

   /**
   * Get jobLevel
   * @return jobLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JobLevel89a0b59e7cce1000074acb3c1e8e015d getJobLevel() {
    return jobLevel;
  }


  public void setJobLevel(JobLevel89a0b59e7cce1000074acb3c1e8e015d jobLevel) {
    
    
    
    this.jobLevel = jobLevel;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf managementLevel(ManagementLevel89a0b59e7cce1000074acb1d768e0158 managementLevel) {
    
    
    
    
    this.managementLevel = managementLevel;
    return this;
  }

   /**
   * Get managementLevel
   * @return managementLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ManagementLevel89a0b59e7cce1000074acb1d768e0158 getManagementLevel() {
    return managementLevel;
  }


  public void setManagementLevel(ManagementLevel89a0b59e7cce1000074acb1d768e0158 managementLevel) {
    
    
    
    this.managementLevel = managementLevel;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf criticalJob(Boolean criticalJob) {
    
    
    
    
    this.criticalJob = criticalJob;
    return this;
  }

   /**
   * Indicates if the job is considered critical.
   * @return criticalJob
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Indicates if the job is considered critical.")

  public Boolean getCriticalJob() {
    return criticalJob;
  }


  public void setCriticalJob(Boolean criticalJob) {
    
    
    
    this.criticalJob = criticalJob;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf jobExempts(List<JobProfileExemptRelatedView3b00708994e41000076da515387812a2> jobExempts) {
    
    
    
    
    this.jobExempts = jobExempts;
    return this;
  }

  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf addJobExemptsItem(JobProfileExemptRelatedView3b00708994e41000076da515387812a2 jobExemptsItem) {
    if (this.jobExempts == null) {
      this.jobExempts = new ArrayList<>();
    }
    this.jobExempts.add(jobExemptsItem);
    return this;
  }

   /**
   * Returns the job exempt instances for the job profile.
   * @return jobExempts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Returns the job exempt instances for the job profile.")

  public List<JobProfileExemptRelatedView3b00708994e41000076da515387812a2> getJobExempts() {
    return jobExempts;
  }


  public void setJobExempts(List<JobProfileExemptRelatedView3b00708994e41000076da515387812a2> jobExempts) {
    
    
    
    this.jobExempts = jobExempts;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf companyInsiderTypes(List<CompanyInsiderTypeRelatedView7deab99f645f10001000f8a388740081> companyInsiderTypes) {
    
    
    
    
    this.companyInsiderTypes = companyInsiderTypes;
    return this;
  }

  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf addCompanyInsiderTypesItem(CompanyInsiderTypeRelatedView7deab99f645f10001000f8a388740081 companyInsiderTypesItem) {
    if (this.companyInsiderTypes == null) {
      this.companyInsiderTypes = new ArrayList<>();
    }
    this.companyInsiderTypes.add(companyInsiderTypesItem);
    return this;
  }

   /**
   * The Company Insider Type for the Job Profile.
   * @return companyInsiderTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The Company Insider Type for the Job Profile.")

  public List<CompanyInsiderTypeRelatedView7deab99f645f10001000f8a388740081> getCompanyInsiderTypes() {
    return companyInsiderTypes;
  }


  public void setCompanyInsiderTypes(List<CompanyInsiderTypeRelatedView7deab99f645f10001000f8a388740081> companyInsiderTypes) {
    
    
    
    this.companyInsiderTypes = companyInsiderTypes;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf defaultJobTitle(String defaultJobTitle) {
    
    
    
    
    this.defaultJobTitle = defaultJobTitle;
    return this;
  }

   /**
   * The Job Title Default for the job profile.
   * @return defaultJobTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The Job Title Default for the job profile.")

  public String getDefaultJobTitle() {
    return defaultJobTitle;
  }


  public void setDefaultJobTitle(String defaultJobTitle) {
    
    
    
    this.defaultJobTitle = defaultJobTitle;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf workShiftRequired(Boolean workShiftRequired) {
    
    
    
    
    this.workShiftRequired = workShiftRequired;
    return this;
  }

   /**
   * Indicates if the Job Profile requires a Work Shift to be specified on associated Positions.
   * @return workShiftRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Indicates if the Job Profile requires a Work Shift to be specified on associated Positions.")

  public Boolean getWorkShiftRequired() {
    return workShiftRequired;
  }


  public void setWorkShiftRequired(Boolean workShiftRequired) {
    
    
    
    this.workShiftRequired = workShiftRequired;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf additionalJobDescription(String additionalJobDescription) {
    
    
    
    
    this.additionalJobDescription = additionalJobDescription;
    return this;
  }

   /**
   * The formatted additional job description value on the job profile.
   * @return additionalJobDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The formatted additional job description value on the job profile.")

  public String getAdditionalJobDescription() {
    return additionalJobDescription;
  }


  public void setAdditionalJobDescription(String additionalJobDescription) {
    
    
    
    this.additionalJobDescription = additionalJobDescription;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf jobFamilies(List<JobFamilyRelatedView3b00708994e410000e0e2540529b12d6> jobFamilies) {
    
    
    
    
    this.jobFamilies = jobFamilies;
    return this;
  }

  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf addJobFamiliesItem(JobFamilyRelatedView3b00708994e410000e0e2540529b12d6 jobFamiliesItem) {
    if (this.jobFamilies == null) {
      this.jobFamilies = new ArrayList<>();
    }
    this.jobFamilies.add(jobFamiliesItem);
    return this;
  }

   /**
   * The job family for the job profile.
   * @return jobFamilies
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The job family for the job profile.")

  public List<JobFamilyRelatedView3b00708994e410000e0e2540529b12d6> getJobFamilies() {
    return jobFamilies;
  }


  public void setJobFamilies(List<JobFamilyRelatedView3b00708994e410000e0e2540529b12d6> jobFamilies) {
    
    
    
    this.jobFamilies = jobFamilies;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf difficultyToFill(DifficultyToFill89a0b59e7cce1000074acb57c0c50162 difficultyToFill) {
    
    
    
    
    this.difficultyToFill = difficultyToFill;
    return this;
  }

   /**
   * Get difficultyToFill
   * @return difficultyToFill
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DifficultyToFill89a0b59e7cce1000074acb57c0c50162 getDifficultyToFill() {
    return difficultyToFill;
  }


  public void setDifficultyToFill(DifficultyToFill89a0b59e7cce1000074acb57c0c50162 difficultyToFill) {
    
    
    
    this.difficultyToFill = difficultyToFill;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * The name of the job profile.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The name of the job profile.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf jobCategory(JobCategory89a0b59e7cce1000074acb471919015f jobCategory) {
    
    
    
    
    this.jobCategory = jobCategory;
    return this;
  }

   /**
   * Get jobCategory
   * @return jobCategory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public JobCategory89a0b59e7cce1000074acb471919015f getJobCategory() {
    return jobCategory;
  }


  public void setJobCategory(JobCategory89a0b59e7cce1000074acb471919015f jobCategory) {
    
    
    
    this.jobCategory = jobCategory;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf payRateTypes(List<JobProfilePayRateTypeRelatedView3b00708994e4100008d4b09e903f12b5> payRateTypes) {
    
    
    
    
    this.payRateTypes = payRateTypes;
    return this;
  }

  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf addPayRateTypesItem(JobProfilePayRateTypeRelatedView3b00708994e4100008d4b09e903f12b5 payRateTypesItem) {
    if (this.payRateTypes == null) {
      this.payRateTypes = new ArrayList<>();
    }
    this.payRateTypes.add(payRateTypesItem);
    return this;
  }

   /**
   * The pay rate for the job profile
   * @return payRateTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The pay rate for the job profile")

  public List<JobProfilePayRateTypeRelatedView3b00708994e4100008d4b09e903f12b5> getPayRateTypes() {
    return payRateTypes;
  }


  public void setPayRateTypes(List<JobProfilePayRateTypeRelatedView3b00708994e4100008d4b09e903f12b5> payRateTypes) {
    
    
    
    this.payRateTypes = payRateTypes;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf restrictedToCountries(List<CountryRelatedView7deab99f645f10000cf305c30e260054> restrictedToCountries) {
    
    
    
    
    this.restrictedToCountries = restrictedToCountries;
    return this;
  }

  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf addRestrictedToCountriesItem(CountryRelatedView7deab99f645f10000cf305c30e260054 restrictedToCountriesItem) {
    if (this.restrictedToCountries == null) {
      this.restrictedToCountries = new ArrayList<>();
    }
    this.restrictedToCountries.add(restrictedToCountriesItem);
    return this;
  }

   /**
   * Returns the valid countries for the job profile.
   * @return restrictedToCountries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Returns the valid countries for the job profile.")

  public List<CountryRelatedView7deab99f645f10000cf305c30e260054> getRestrictedToCountries() {
    return restrictedToCountries;
  }


  public void setRestrictedToCountries(List<CountryRelatedView7deab99f645f10000cf305c30e260054> restrictedToCountries) {
    
    
    
    this.restrictedToCountries = restrictedToCountries;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf workersCompensationCodes(List<WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287> workersCompensationCodes) {
    
    
    
    
    this.workersCompensationCodes = workersCompensationCodes;
    return this;
  }

  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf addWorkersCompensationCodesItem(WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287 workersCompensationCodesItem) {
    if (this.workersCompensationCodes == null) {
      this.workersCompensationCodes = new ArrayList<>();
    }
    this.workersCompensationCodes.add(workersCompensationCodesItem);
    return this;
  }

   /**
   * Returns the compensation codes for this job profile.
   * @return workersCompensationCodes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Returns the compensation codes for this job profile.")

  public List<WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287> getWorkersCompensationCodes() {
    return workersCompensationCodes;
  }


  public void setWorkersCompensationCodes(List<WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287> workersCompensationCodes) {
    
    
    
    this.workersCompensationCodes = workersCompensationCodes;
  }


  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Id of the instance
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Id of the instance")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf instance itself
   */
  public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf = (JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf) o;
    return Objects.equals(this.summary, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.summary) &&
        Objects.equals(this.jobDescription, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.jobDescription) &&
        Objects.equals(this.inactive, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.inactive) &&
        Objects.equals(this._public, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf._public) &&
        Objects.equals(this.jobLevel, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.jobLevel) &&
        Objects.equals(this.managementLevel, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.managementLevel) &&
        Objects.equals(this.criticalJob, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.criticalJob) &&
        Objects.equals(this.jobExempts, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.jobExempts) &&
        Objects.equals(this.companyInsiderTypes, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.companyInsiderTypes) &&
        Objects.equals(this.defaultJobTitle, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.defaultJobTitle) &&
        Objects.equals(this.workShiftRequired, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.workShiftRequired) &&
        Objects.equals(this.additionalJobDescription, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.additionalJobDescription) &&
        Objects.equals(this.jobFamilies, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.jobFamilies) &&
        Objects.equals(this.difficultyToFill, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.difficultyToFill) &&
        Objects.equals(this.name, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.name) &&
        Objects.equals(this.jobCategory, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.jobCategory) &&
        Objects.equals(this.payRateTypes, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.payRateTypes) &&
        Objects.equals(this.restrictedToCountries, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.restrictedToCountries) &&
        Objects.equals(this.workersCompensationCodes, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.workersCompensationCodes) &&
        Objects.equals(this.id, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.id)&&
        Objects.equals(this.additionalProperties, jobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(summary, jobDescription, inactive, _public, jobLevel, managementLevel, criticalJob, jobExempts, companyInsiderTypes, defaultJobTitle, workShiftRequired, additionalJobDescription, jobFamilies, difficultyToFill, name, jobCategory, payRateTypes, restrictedToCountries, workersCompensationCodes, id, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf {\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    jobDescription: ").append(toIndentedString(jobDescription)).append("\n");
    sb.append("    inactive: ").append(toIndentedString(inactive)).append("\n");
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("    jobLevel: ").append(toIndentedString(jobLevel)).append("\n");
    sb.append("    managementLevel: ").append(toIndentedString(managementLevel)).append("\n");
    sb.append("    criticalJob: ").append(toIndentedString(criticalJob)).append("\n");
    sb.append("    jobExempts: ").append(toIndentedString(jobExempts)).append("\n");
    sb.append("    companyInsiderTypes: ").append(toIndentedString(companyInsiderTypes)).append("\n");
    sb.append("    defaultJobTitle: ").append(toIndentedString(defaultJobTitle)).append("\n");
    sb.append("    workShiftRequired: ").append(toIndentedString(workShiftRequired)).append("\n");
    sb.append("    additionalJobDescription: ").append(toIndentedString(additionalJobDescription)).append("\n");
    sb.append("    jobFamilies: ").append(toIndentedString(jobFamilies)).append("\n");
    sb.append("    difficultyToFill: ").append(toIndentedString(difficultyToFill)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    jobCategory: ").append(toIndentedString(jobCategory)).append("\n");
    sb.append("    payRateTypes: ").append(toIndentedString(payRateTypes)).append("\n");
    sb.append("    restrictedToCountries: ").append(toIndentedString(restrictedToCountries)).append("\n");
    sb.append("    workersCompensationCodes: ").append(toIndentedString(workersCompensationCodes)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("summary");
    openapiFields.add("jobDescription");
    openapiFields.add("inactive");
    openapiFields.add("public");
    openapiFields.add("jobLevel");
    openapiFields.add("managementLevel");
    openapiFields.add("criticalJob");
    openapiFields.add("jobExempts");
    openapiFields.add("companyInsiderTypes");
    openapiFields.add("defaultJobTitle");
    openapiFields.add("workShiftRequired");
    openapiFields.add("additionalJobDescription");
    openapiFields.add("jobFamilies");
    openapiFields.add("difficultyToFill");
    openapiFields.add("name");
    openapiFields.add("jobCategory");
    openapiFields.add("payRateTypes");
    openapiFields.add("restrictedToCountries");
    openapiFields.add("workersCompensationCodes");
    openapiFields.add("id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf is not found in the empty JSON string", JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("summary") != null && !jsonObj.get("summary").isJsonNull()) && !jsonObj.get("summary").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `summary` to be a primitive type in the JSON string but got `%s`", jsonObj.get("summary").toString()));
      }
      if ((jsonObj.get("jobDescription") != null && !jsonObj.get("jobDescription").isJsonNull()) && !jsonObj.get("jobDescription").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `jobDescription` to be a primitive type in the JSON string but got `%s`", jsonObj.get("jobDescription").toString()));
      }
      // validate the optional field `jobLevel`
      if (jsonObj.get("jobLevel") != null && !jsonObj.get("jobLevel").isJsonNull()) {
        JobLevel89a0b59e7cce1000074acb3c1e8e015d.validateJsonObject(jsonObj.getAsJsonObject("jobLevel"));
      }
      // validate the optional field `managementLevel`
      if (jsonObj.get("managementLevel") != null && !jsonObj.get("managementLevel").isJsonNull()) {
        ManagementLevel89a0b59e7cce1000074acb1d768e0158.validateJsonObject(jsonObj.getAsJsonObject("managementLevel"));
      }
      if (jsonObj.get("jobExempts") != null && !jsonObj.get("jobExempts").isJsonNull()) {
        JsonArray jsonArrayjobExempts = jsonObj.getAsJsonArray("jobExempts");
        if (jsonArrayjobExempts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("jobExempts").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `jobExempts` to be an array in the JSON string but got `%s`", jsonObj.get("jobExempts").toString()));
          }

          // validate the optional field `jobExempts` (array)
          for (int i = 0; i < jsonArrayjobExempts.size(); i++) {
            JobProfileExemptRelatedView3b00708994e41000076da515387812a2.validateJsonObject(jsonArrayjobExempts.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("companyInsiderTypes") != null && !jsonObj.get("companyInsiderTypes").isJsonNull()) {
        JsonArray jsonArraycompanyInsiderTypes = jsonObj.getAsJsonArray("companyInsiderTypes");
        if (jsonArraycompanyInsiderTypes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("companyInsiderTypes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `companyInsiderTypes` to be an array in the JSON string but got `%s`", jsonObj.get("companyInsiderTypes").toString()));
          }

          // validate the optional field `companyInsiderTypes` (array)
          for (int i = 0; i < jsonArraycompanyInsiderTypes.size(); i++) {
            CompanyInsiderTypeRelatedView7deab99f645f10001000f8a388740081.validateJsonObject(jsonArraycompanyInsiderTypes.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("defaultJobTitle") != null && !jsonObj.get("defaultJobTitle").isJsonNull()) && !jsonObj.get("defaultJobTitle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `defaultJobTitle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("defaultJobTitle").toString()));
      }
      if ((jsonObj.get("additionalJobDescription") != null && !jsonObj.get("additionalJobDescription").isJsonNull()) && !jsonObj.get("additionalJobDescription").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `additionalJobDescription` to be a primitive type in the JSON string but got `%s`", jsonObj.get("additionalJobDescription").toString()));
      }
      if (jsonObj.get("jobFamilies") != null && !jsonObj.get("jobFamilies").isJsonNull()) {
        JsonArray jsonArrayjobFamilies = jsonObj.getAsJsonArray("jobFamilies");
        if (jsonArrayjobFamilies != null) {
          // ensure the json data is an array
          if (!jsonObj.get("jobFamilies").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `jobFamilies` to be an array in the JSON string but got `%s`", jsonObj.get("jobFamilies").toString()));
          }

          // validate the optional field `jobFamilies` (array)
          for (int i = 0; i < jsonArrayjobFamilies.size(); i++) {
            JobFamilyRelatedView3b00708994e410000e0e2540529b12d6.validateJsonObject(jsonArrayjobFamilies.get(i).getAsJsonObject());
          };
        }
      }
      // validate the optional field `difficultyToFill`
      if (jsonObj.get("difficultyToFill") != null && !jsonObj.get("difficultyToFill").isJsonNull()) {
        DifficultyToFill89a0b59e7cce1000074acb57c0c50162.validateJsonObject(jsonObj.getAsJsonObject("difficultyToFill"));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `jobCategory`
      if (jsonObj.get("jobCategory") != null && !jsonObj.get("jobCategory").isJsonNull()) {
        JobCategory89a0b59e7cce1000074acb471919015f.validateJsonObject(jsonObj.getAsJsonObject("jobCategory"));
      }
      if (jsonObj.get("payRateTypes") != null && !jsonObj.get("payRateTypes").isJsonNull()) {
        JsonArray jsonArraypayRateTypes = jsonObj.getAsJsonArray("payRateTypes");
        if (jsonArraypayRateTypes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("payRateTypes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `payRateTypes` to be an array in the JSON string but got `%s`", jsonObj.get("payRateTypes").toString()));
          }

          // validate the optional field `payRateTypes` (array)
          for (int i = 0; i < jsonArraypayRateTypes.size(); i++) {
            JobProfilePayRateTypeRelatedView3b00708994e4100008d4b09e903f12b5.validateJsonObject(jsonArraypayRateTypes.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("restrictedToCountries") != null && !jsonObj.get("restrictedToCountries").isJsonNull()) {
        JsonArray jsonArrayrestrictedToCountries = jsonObj.getAsJsonArray("restrictedToCountries");
        if (jsonArrayrestrictedToCountries != null) {
          // ensure the json data is an array
          if (!jsonObj.get("restrictedToCountries").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `restrictedToCountries` to be an array in the JSON string but got `%s`", jsonObj.get("restrictedToCountries").toString()));
          }

          // validate the optional field `restrictedToCountries` (array)
          for (int i = 0; i < jsonArrayrestrictedToCountries.size(); i++) {
            CountryRelatedView7deab99f645f10000cf305c30e260054.validateJsonObject(jsonArrayrestrictedToCountries.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("workersCompensationCodes") != null && !jsonObj.get("workersCompensationCodes").isJsonNull()) {
        JsonArray jsonArrayworkersCompensationCodes = jsonObj.getAsJsonArray("workersCompensationCodes");
        if (jsonArrayworkersCompensationCodes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("workersCompensationCodes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `workersCompensationCodes` to be an array in the JSON string but got `%s`", jsonObj.get("workersCompensationCodes").toString()));
          }

          // validate the optional field `workersCompensationCodes` (array)
          for (int i = 0; i < jsonArrayworkersCompensationCodes.size(); i++) {
            WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287.validateJsonObject(jsonArrayworkersCompensationCodes.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.class));

       return (TypeAdapter<T>) new TypeAdapter<JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf>() {
           @Override
           public void write(JsonWriter out, JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf
  * @throws IOException if the JSON string is invalid with respect to JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf
  */
  public static JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf.class);
  }

 /**
  * Convert an instance of JobProfileDetailView7deab99f645f10000bd5e61a1b780041AllOf to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

