/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CustomOrganizationDetails3950e273020a100017857926d35d369c;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf {
  public static final String SERIALIZED_NAME_CUSTOM_ORGANIZATIONS = "customOrganizations";
  @SerializedName(SERIALIZED_NAME_CUSTOM_ORGANIZATIONS)
  private List<CustomOrganizationDetails3950e273020a100017857926d35d369c> customOrganizations = null;

  public OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf() {
  }

  public OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf customOrganizations(List<CustomOrganizationDetails3950e273020a100017857926d35d369c> customOrganizations) {
    
    
    
    
    this.customOrganizations = customOrganizations;
    return this;
  }

  public OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf addCustomOrganizationsItem(CustomOrganizationDetails3950e273020a100017857926d35d369c customOrganizationsItem) {
    if (this.customOrganizations == null) {
      this.customOrganizations = new ArrayList<>();
    }
    this.customOrganizations.add(customOrganizationsItem);
    return this;
  }

   /**
   * The new custom organizations for the worker as of the effective date.
   * @return customOrganizations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The new custom organizations for the worker as of the effective date.")

  public List<CustomOrganizationDetails3950e273020a100017857926d35d369c> getCustomOrganizations() {
    return customOrganizations;
  }


  public void setCustomOrganizations(List<CustomOrganizationDetails3950e273020a100017857926d35d369c> customOrganizations) {
    
    
    
    this.customOrganizations = customOrganizations;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf instance itself
   */
  public OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf organizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf = (OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf) o;
    return Objects.equals(this.customOrganizations, organizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf.customOrganizations)&&
        Objects.equals(this.additionalProperties, organizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customOrganizations, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf {\n");
    sb.append("    customOrganizations: ").append(toIndentedString(customOrganizations)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("customOrganizations");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf is not found in the empty JSON string", OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("customOrganizations") != null && !jsonObj.get("customOrganizations").isJsonNull()) {
        JsonArray jsonArraycustomOrganizations = jsonObj.getAsJsonArray("customOrganizations");
        if (jsonArraycustomOrganizations != null) {
          // ensure the json data is an array
          if (!jsonObj.get("customOrganizations").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `customOrganizations` to be an array in the JSON string but got `%s`", jsonObj.get("customOrganizations").toString()));
          }

          // validate the optional field `customOrganizations` (array)
          for (int i = 0; i < jsonArraycustomOrganizations.size(); i++) {
            CustomOrganizationDetails3950e273020a100017857926d35d369c.validateJsonObject(jsonArraycustomOrganizations.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf.class));

       return (TypeAdapter<T>) new TypeAdapter<OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf>() {
           @Override
           public void write(JsonWriter out, OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf
  * @throws IOException if the JSON string is invalid with respect to OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf
  */
  public static OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf.class);
  }

 /**
  * Convert an instance of OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

