/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 {
  public static final String SERIALIZED_NAME_SKILL_NAME = "skillName";
  @SerializedName(SERIALIZED_NAME_SKILL_NAME)
  private String skillName;

  public static final String SERIALIZED_NAME_REMOTE_I_D = "remoteID";
  @SerializedName(SERIALIZED_NAME_REMOTE_I_D)
  private String remoteID;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_DESCRIPTOR = "descriptor";
  @SerializedName(SERIALIZED_NAME_DESCRIPTOR)
  private String descriptor;

  public SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8() {
  }

  public SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 skillName(String skillName) {
    
    
    
    
    this.skillName = skillName;
    return this;
  }

   /**
   * The skill name that Workday bases similar skill suggestions on.
   * @return skillName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The skill name that Workday bases similar skill suggestions on.")

  public String getSkillName() {
    return skillName;
  }


  public void setSkillName(String skillName) {
    
    
    
    this.skillName = skillName;
  }


  public SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 remoteID(String remoteID) {
    
    
    
    
    this.remoteID = remoteID;
    return this;
  }

   /**
   * The remote skill ID of a skill.
   * @return remoteID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The remote skill ID of a skill.")

  public String getRemoteID() {
    return remoteID;
  }


  public void setRemoteID(String remoteID) {
    
    
    
    this.remoteID = remoteID;
  }


  public SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Id of the instance
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Id of the instance")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 descriptor(String descriptor) {
    
    
    
    
    this.descriptor = descriptor;
    return this;
  }

   /**
   * A preview of the instance
   * @return descriptor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit ame", value = "A preview of the instance")

  public String getDescriptor() {
    return descriptor;
  }


  public void setDescriptor(String descriptor) {
    
    
    
    this.descriptor = descriptor;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 instance itself
   */
  public SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 skillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 = (SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8) o;
    return Objects.equals(this.skillName, skillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8.skillName) &&
        Objects.equals(this.remoteID, skillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8.remoteID) &&
        Objects.equals(this.id, skillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8.id) &&
        Objects.equals(this.descriptor, skillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8.descriptor)&&
        Objects.equals(this.additionalProperties, skillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(skillName, remoteID, id, descriptor, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 {\n");
    sb.append("    skillName: ").append(toIndentedString(skillName)).append("\n");
    sb.append("    remoteID: ").append(toIndentedString(remoteID)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    descriptor: ").append(toIndentedString(descriptor)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("skillName");
    openapiFields.add("remoteID");
    openapiFields.add("id");
    openapiFields.add("descriptor");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 is not found in the empty JSON string", SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("skillName") != null && !jsonObj.get("skillName").isJsonNull()) && !jsonObj.get("skillName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `skillName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("skillName").toString()));
      }
      if ((jsonObj.get("remoteID") != null && !jsonObj.get("remoteID").isJsonNull()) && !jsonObj.get("remoteID").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `remoteID` to be a primitive type in the JSON string but got `%s`", jsonObj.get("remoteID").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("descriptor") != null && !jsonObj.get("descriptor").isJsonNull()) && !jsonObj.get("descriptor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `descriptor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("descriptor").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8.class));

       return (TypeAdapter<T>) new TypeAdapter<SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8>() {
           @Override
           public void write(JsonWriter out, SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8
  * @throws IOException if the JSON string is invalid with respect to SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8
  */
  public static SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8.class);
  }

 /**
  * Convert an instance of SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

