/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ERRORMODELREFERENCE;
import com.konfigthis.client.model.JobFamiliesListResponse;
import com.konfigthis.client.model.JobFamilyView51ed1475e9e6100005d10fcedc5a000a;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for JobFamiliesApi
 */
@Disabled
public class JobFamiliesApiTest {

    private static JobFamiliesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new JobFamiliesApi(apiClient);
    }

    /**
     * Retrieves a single job family instance.
     *
     * Retrieves a job family with the specified ID.  Secured by: Job Information  Scope: Jobs &amp; Positions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        String ID = null;
        JobFamilyView51ed1475e9e6100005d10fcedc5a000a response = api.getById(ID)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieves a collection of job families.
     *
     * Retrieves a collection of job families.  Secured by: Job Information  Scope: Jobs &amp; Positions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTest() throws ApiException {
        Boolean inactive = null;
        List<String> jobFamilyGroup = null;
        List<String> jobProfile = null;
        Long limit = null;
        Long offset = null;
        JobFamiliesListResponse response = api.list()
                .inactive(inactive)
                .jobFamilyGroup(jobFamilyGroup)
                .jobProfile(jobProfile)
                .limit(limit)
                .offset(offset)
                .execute();
        // TODO: test validations
    }

}
