/*
 * staffing
 * The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.    Related Information: - Administrator Guide: Setup Considerations: Job Changes
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ERRORMODELREFERENCE;
import com.konfigthis.client.model.JobProfileDetailView7deab99f645f10000bd5e61a1b780041;
import com.konfigthis.client.model.JobProfilesListCollectionResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for JobProfilesApi
 */
@Disabled
public class JobProfilesApiTest {

    private static JobProfilesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new JobProfilesApi(apiClient);
    }

    /**
     * Retrieves a single job profile instance.
     *
     * Retrieves a job profile with the specified ID.  Secured by: Job Profile: View, Public Job: View  Scope: Jobs &amp; Positions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        String ID = null;
        JobProfileDetailView7deab99f645f10000bd5e61a1b780041 response = api.getById(ID)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieves a collection of job profiles.
     *
     * Retrieves a collection of job profiles.  Secured by: Job Profile: View, Public Job: View  Scope: Jobs &amp; Positions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCollectionTest() throws ApiException {
        Boolean includeInactive = null;
        Long limit = null;
        Long offset = null;
        JobProfilesListCollectionResponse response = api.listCollection()
                .includeInactive(includeInactive)
                .limit(limit)
                .offset(offset)
                .execute();
        // TODO: test validations
    }

}
